name: pystats

"on": [pull_request]

jobs:
  collect-stats:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sha: [
          "${{ github.event.pull_request.head.sha }}",
          "${{ github.event.pull_request.base.sha }}"
        ]
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ matrix.sha }}
    - name: Cache
      id: cache
      uses: actions/cache@v3
      with:
        path: install
        key: install-${{ matrix.sha }}
    - name: Install Dependencies
      run: sudo ./.github/workflows/posix-deps-apt.sh
    - name: Add ccache to PATH
      run: |
        echo "PATH=/usr/lib/ccache:$PATH" >> $GITHUB_ENV
    - name: Configure ccache action
      uses: hendrikmuhs/ccache-action@v1
    - name: Create pystats directory
      run: |
        mkdir /tmp/py_stats
    - name: Compile
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        ./configure --enable-pystats --prefix=$PWD/install
        make -j4
        make install
    - name: Install pyperformance
      run: |
        ./install/bin/python3 -m venv venv
        source venv/bin/activate
        python -m pip install git+https://github.com/python/pyperformance@c457e5b
    - name: Collect stats
      run: |
        source venv/bin/activate
        # Delete any stats collected during pip install etc.
        rm /tmp/py_stats/*
        pyperformance run || echo "done"
    - name: Summarize stats
      run: |
        source venv/bin/activate
        # Needs to run in same version of Python as build
        git checkout ${{ github.event.pull_request.head.sha }} Tools/scripts/summarize_stats.py  # REMOVE ME
        python Tools/scripts/summarize_stats.py --json-output pystats-${{ matrix.sha }}.json
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: pystats-${{ matrix.sha }}
        path: pystats-${{ matrix.sha }}.json

  summarize_stats:
    runs-on: ubuntu-latest
    needs: [collect-stats]
    steps:
    - uses: actions/checkout@v3
    - name: Cache
      id: cache
      uses: actions/cache@v3
      with:
        path: install
        key: install-${{ github.event.pull_request.base.sha }}
    - name: Download artifacts
      uses: actions/download-artifact@v3
    - name: Summarize results
      run: |
        ./install/bin/python3 Tools/scripts/summarize_stats.py pystats-${{ github.event.pull_request.base.sha }}.json pystats-${{ github.event.pull_request.head.sha }}.json
        ./install/bin/python3 Tools/scripts/summarize_stats.py pystats-${{ github.event.pull_request.base.sha }}.json pystats-${{ github.event.pull_request.head.sha }}.json &> pystats-results.md
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: pystats
        path: pystats-results.md
    - name: Add comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body-file: pystats-results.md
        token: ${{ secrets.COMMENT_TOKEN }}
