name: pystats

"on": [pull_request]

jobs:
  collect-stats:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sha: [
          "${{ github.event.pull_request.head.sha }}",
          "${{ github.event.pull_request.base.sha }}"
        ]
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ matrix.sha }}
    - name: Cache
      id: cache
      uses: actions/cache@v3
      with:
        path: install
        key: install-${{ matrix.sha }}
    - name: Install Dependencies
      run: sudo ./.github/workflows/posix-deps-apt.sh
    - name: Add ccache to PATH
      run: |
        echo "PATH=/usr/lib/ccache:$PATH" >> $GITHUB_ENV
    - name: Configure ccache action
      uses: hendrikmuhs/ccache-action@v1.2
    - name: Create pystats directory
      run: |
        # If we don't do this, stats are printed to the console
        mkdir /tmp/py_stats
    - name: Compile
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        ./configure --enable-pystats --prefix=$PWD/install
        make -j4
        make install
    - name: Install pyperformance into the system python
      run: |
        python -m pip install git+https://github.com/mdboom/pyperf@925f07b  # REMOVE ME
        python -m pip install git+https://github.com/python/pyperformance@c457e5b
    - name: Collect stats
      run: |
        # Run pyperformance itself on the system python, so it doesn't collect stats.
        # The benchmarks themselves are run using the python we built here.
        pyperformance run --output results-${{ matrix.sha }}.json --python ./install/bin/python3 || echo "done"
    - name: Summarize stats
      run: |
        git fetch origin  # REMOVE ME
        git checkout ${{ github.event.pull_request.head.sha }} Tools/scripts/summarize_stats.py  # REMOVE ME
        # Needs to run in same version of Python as build so the opcodes and source files match
        ./install/bin/python3 Tools/scripts/summarize_stats.py --json-output pystats-${{ matrix.sha }}.json &> /dev/null
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pystats-${{ matrix.sha }}
        path: "*.json"

  summarize_stats:
    runs-on: ubuntu-latest
    needs: [collect-stats]
    steps:
    - uses: actions/checkout@v3
    - name: Cache
      id: cache
      uses: actions/cache@v3
      with:
        path: install
        key: install-${{ github.event.pull_request.base.sha }}
    - name: Download artifacts
      uses: actions/download-artifact@v3
    - name: Summarize results
      run: |
        # If we don't do this, stats are printed to the console
        mkdir /tmp/py_stats
        ./install/bin/python3 Tools/scripts/summarize_stats.py pystats-${{ github.event.pull_request.base.sha }}/pystats-${{ github.event.pull_request.base.sha }}.json pystats-${{ github.event.pull_request.head.sha }}/pystats-${{ github.event.pull_request.head.sha }}.json
        # Base stats
        ./install/bin/python3 Tools/scripts/summarize_stats.py pystats-${{ github.event.pull_request.base.sha }}/pystats-${{ github.event.pull_request.base.sha }}.json
        # Head stats
        ./install/bin/python3 Tools/scripts/summarize_stats.py pystats-${{ github.event.pull_request.head.sha }}/pystats-${{ github.event.pull_request.head.sha }}.json
        # Comparative stats
        ./install/bin/python3 Tools/scripts/summarize_stats.py pystats-${{ github.event.pull_request.base.sha }}/pystats-${{ github.event.pull_request.base.sha }}.json pystats-${{ github.event.pull_request.head.sha }}/pystats-${{ github.event.pull_request.head.sha }}.json &> pystats-comparative.md
        # Base stats
        ./install/bin/python3 Tools/scripts/summarize_stats.py pystats-${{ github.event.pull_request.base.sha }}/pystats-${{ github.event.pull_request.base.sha }}.json &> pystats-${{ github.event.pull_request.base.sha }}.md
        # Head stats
        ./install/bin/python3 Tools/scripts/summarize_stats.py pystats-${{ github.event.pull_request.head.sha }}/pystats-${{ github.event.pull_request.head.sha }}.json &> pystats-${{ github.event.pull_request.head.sha }}.md
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pystats
        path: "*.md"
    - name: Add comment comparative
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body-file: pystats-comparative.md
        token: ${{ secrets.COMMENT_TOKEN }}
    - name: Add comment base
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body-file: pystats-${{ github.event.pull_request.base.sha }}.md
        token: ${{ secrets.COMMENT_TOKEN }}
    - name: Add comment head
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body-file: pystats-${{ github.event.pull_request.head.sha }}.md
        token: ${{ secrets.COMMENT_TOKEN }}
